- name: Install Zabbix repository RPM using yum
  ansible.builtin.yum:
    name: https://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
    state: present

- name: Install Zabbix Agent using yum
  ansible.builtin.yum:
    name: zabbix-agent
    state: present
  notify:
    - Restart zabbix-agent
    - Enable zabbix-agent

- name: Update Zabbix Agent configuration file - Server value
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server=127.0.0.1'
    line: 'Server=192.168.1.181'
  notify:
    - Restart zabbix-agent

- name: Update Zabbix Agent configuration file - ServerActive value
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive=127.0.0.1'
    line: 'ServerActive=192.168.1.181'
  notify:
    - Restart zabbix-agent

- name: Add port 10050 to firewall
  firewalld:
    port: 10050/tcp
    permanent: true
    state: enabled
  notify:
    - Restart Firewalld
