- name: OS debug
  debug: 
    var: ansible_facts.os_family
- name: Major version debug
  debug: 
    var: ansible_distribution_major_version
    
- block:
  - name: Set zabbix_agentd_path rhel7 or XCP-ng 8
    set_fact:
      zabbix_agentd_path: /etc/zabbix/zabbix_agentd.conf
#    when: ansible_facts.os_family == 'RedHat' and ansible_distribution_major_version == "7" 
    when: (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == "7") or (ansible_facts['os_family'] == 'XCP-ng' and ansible_facts['distribution_major_version'] == "8")

  - name: Set zabbix_agentd_path rhel8-9 
    set_fact:
      zabbix_agentd_path: /etc/zabbix_agentd.conf
    when: ansible_facts.os_family == 'RedHat' and ansible_distribution_major_version >= "8"

  - name: debug zabbix_agentd_path
    debug: 
      var: zabbix_agentd_path
    
  - name: Install Zabbix repository RPM using yum
    ansible.builtin.yum:
      name: https://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
      state: present
      disable_gpg_check: true
  
  - name: Install Zabbix Agent using yum
    ansible.builtin.yum:
      name: zabbix-agent
      state: present
    notify:
      - Restart zabbix-agent
      - Enable zabbix-agent
      
  - meta: flush_handlers
  
  - name: Update Zabbix Agent configuration file - Server value
    ansible.builtin.lineinfile:
      path: "{{ zabbix_agentd_path }}"
      regexp: '^Server=127.0.0.1'
      line: 'Server=192.168.1.181'
    notify:
      - Restart zabbix-agent
  
  - name: Update Zabbix Agent configuration file - ServerActive value
    ansible.builtin.lineinfile:
      path: "{{ zabbix_agentd_path }}"
      regexp: '^ServerActive=127.0.0.1'
      line: 'ServerActive=192.168.1.181'
    notify:
      - Restart zabbix-agent
  
  - name: Update Zabbix Agent configuration file with dynamic hostname
    ansible.builtin.replace:
      path: "{{ zabbix_agentd_path }}"
      regexp: '^Hostname=Zabbix server'
      replace: 'Hostname={{ ansible_hostname }}'
    notify:
      - Restart zabbix-agent
  
  - name: Add port 10050 to firewall
    firewalld:
      port: 10050/tcp
      permanent: true
      state: enabled
    notify:
      - Restart Firewalld
    when: (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] >= "7")

  - name: Allow new incoming SYN packets on TCP port 10050 (zabbix)
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 10050
      ctstate: NEW
      syn: match
      jump: ACCEPT
      comment: Accept new zabbix connections
    when: (ansible_facts['os_family'] == 'XCP-ng' and ansible_facts['distribution_major_version'] == "8")

  - name: Notify zabbix-agent start and enable
    notify: 
      - Restart zabbix-agent
      - Enable zabbix-agent
    
  #- name: Add port 10050 to firewall
  #  firewalld:
  #    port: 10051/tcp
  #    permanent: true
  #    state: enabled
  #  notify:
  #    - Restart Firewalld
  #when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '7'"
  when: (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] >= "7") or (ansible_facts['os_family'] == 'XCP-ng' and ansible_facts['distribution_major_version'] == "8")

- block:
  - name: Set zabbix_agentd_path Debian
    set_fact:
      zabbix_agentd_path: /etc/zabbix/zabbix_agentd.conf
    when: ansible_facts.os_family == 'Debian' and ansible_distribution_major_version == "12"

  - name: zabbix_agentd_path
    debug: 
      var: zabbix_agentd_path

  - name: adding repository
    apt:
      deb: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian12_all.deb
      state: present
    
  - name: Install Zabbix Agent using apt
    ansible.builtin.apt:
      name: zabbix-agent
      state: present
    notify:
      - Restart zabbix-agent
      - Enable zabbix-agent
      
  - meta: flush_handlers
  
  - name: Update Zabbix Agent configuration file - Server value
    ansible.builtin.lineinfile:
      path: "{{ zabbix_agentd_path }}"
      regexp: '^Server=127.0.0.1'
      line: 'Server=192.168.1.181'
    notify:
      - Restart zabbix-agent
  
  - name: Update Zabbix Agent configuration file - ServerActive value
    ansible.builtin.lineinfile:
      path: "{{ zabbix_agentd_path }}"
      regexp: '^ServerActive=127.0.0.1'
      line: 'ServerActive=192.168.1.181'
    notify:
      - Restart zabbix-agent
  
  - name: Update Zabbix Agent configuration file with dynamic hostname
    ansible.builtin.replace:
      path: "{{ zabbix_agentd_path }}"
      regexp: '^Hostname=Zabbix server'
      replace: 'Hostname={{ ansible_hostname }}'
    notify:
      - Restart zabbix-agent
  
  - name: Allow new incoming SYN packets on TCP port 10050 (zabbix)
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 10050
      ctstate: NEW
      syn: match
      jump: ACCEPT
      comment: Accept new zabbix connections
      
  #- name: Add port 10050 to firewall
  #  firewalld:
  #    port: 10051/tcp
  #    permanent: true
  #    state: enabled
  #  notify:
  #    - Restart Firewalld
  when: ansible_facts.os_family == 'Debian' and ansible_distribution_major_version == "12"


