---
- name: Restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted

- name: Enable zabbix-agent
  ansible.builtin.systemd:
    name: zabbix-agent
    enabled: yes

- name: Restart Firewalld
  systemd:
    name: firewalld
    state: restarted
    
- name: Restart iptables
  systemd:
    name: iptables
    state: restarted

- name: Save iptables
  command:
    cmd: "iptables-save"

